version: "3.1"

services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.23
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --lower_case_table_names=0 --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: jolboo2022
    ports:
      - 3306:3306
    networks:
      - mysql8

networks:
  mysql8:
    name: mysql8
    external: true


volumes:
  db_data: