spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none

logging:
  level:
    com.jolboo.stock: debug
